######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 7 23:07:25 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += EventDelegate.h GalendarForm.h ProjectDelegate.h ui_EventTimeWidget.h
FORMS += GalendarForm.ui
SOURCES += EventDelegate.cpp GalendarForm.cpp main.cpp ProjectDelegate.cpp
include(qmake.conf)